# -*- coding: utf-8 -*-
"""alt_constructor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uc3LaIizjgJlpQ4NhWqKUReKM55hFvkd
"""

class employee:
  def __init__(self, name, salary):
    self.name = name
    self.salary = salary

e = employee("abc",12000)
print(e.name)
print(e.salary)
string = "john-12000"
e = employee(string.split("-")[0],string.split("-")[1])
print(e.name)
print(e.salary)

# creating class instance
class employee:
  def __init__(self, name, salary):
    self.name = name
    self.salary = salary
  @classmethod
  def fromstr(cls,string):
    return cls(string.split("-")[0], string.split("-")[1])


e1 = employee("abc",12000)
print(e1.name)
print(e1.salary)

string = "john-12000"
e2 = employee.fromstr(string)
print(e2.name)
print(e2.salary)

class person:
  def __init__(self, name, age):
    self.name = name
    self.age = age

  @classmethod
  def from_string(cls,string):
    name,age = string.split(',')
    return cls(name, int(age))

person = person.from_string("john doe, 30")
print(person.name, person.age)