# -*- coding: utf-8 -*-
"""built_in_functions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jngt3958UljpCzycbCHUN0m1EoJS6kLX
"""

x =[1,2,3]    # list
print(dir(x))   # prints all methods and attributes

print(x.__add__)

print(dir(x.__add__))



x = (1,2,3)  # tuple
print(dir(x))
print(x.__class__)
print(x.__add__)
print(x.__doc__)
print(x.__eq__)
print(x.__ge__)
print(x.__lt__)

class person:
  def __init__(self,name,age):
    self.name = name
    self.age = age

p = person("aisha",17)
p.__dict__

class person:
  def __init__(self,name,age):
    self.name = name
    self.age = age
    self.version = 1
p = person("aisha",17)
print(p.__dict__)

# help method() --- used to get help documentation from the object including the decription of attributes and its methods
print(help(person))

