# -*- coding: utf-8 -*-
"""Calculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zl65RC8NUvw_RWp7yhBLck8Ur5co3GXe
"""

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
add = a+b
print("sum of ",a ,"and", b ,"=", add )
difference = a-b
print("Difference of ",a ,"and", b ,"=", difference )
div = a/b
print("quotient of ",a ,"and", b ,"=", div )
mul = a*b
print("product of ",a ,"and", b ,"=", mul )