# -*- coding: utf-8 -*-
"""classmethods.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10B1B3XhuWAPV014WoDGHJN2Q42xIADDT
"""

class employee:
  company = "Apple"
  def show(self):
    print(f"the name is {self.name} and company is {self.company}")

  def changecompany(cls, newcompany):
    cls.company = newcompany

e1 = employee()
e1.name = "Harry"
e1.show()
e1.changecompany("Tesla")

e1.show()

class employee:
  company = "Apple"
  def show(self):
    print(f"the name is {self.name} and company is {self.company}")

  def changecompany(cls, newcompany):
    cls.company = newcompany

e1 = employee()
e1.name = "Harry"
e1.show()
e1.changecompany("Tesla")
e1.show()
print(employee.company)      # it will print apple here

class employee:
  company = "Apple"
  def show(self):
    print(f"the name is {self.name} and company is {self.company}")
  @classmethod
  def changecompany(cls, newcompany):
    cls.company = newcompany

e1 = employee()
e1.name = "Harry"
e1.show()
e1.changecompany("Tesla")
e1.show()