# -*- coding: utf-8 -*-
"""classinstance.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DDDfc3EHYPOSsEe212DCxr75PtTr4QyC
"""

class employee:
  companyname = "Apple"
  noofemp = 0
  def __init__(self, name):
    self.name = name
    self.raise_amount = 2
    employee.noofemp +=1
  def showdetails(self):
    print(f"the name of the employee is {self.name} and the raise amount in {self.noofemp} sized {self.companyname}  is {self.raise_amount}")
#employee.showdetails(emp1)
emp1 = employee("Harry")
emp1.raise_amount = 0.03
emp1.companyname = "apple India"
emp1.showdetails()
employee.companyname = "google"
print(employee.companyname)
# emp2.companyname = "nestle"
#emp2 = employee("Rohan")
# emp2.showdetails()