# -*- coding: utf-8 -*-
"""codelanguage.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ouR3dGu52-8hxBe_7kGYn-eHtP1EyPn0
"""

st = input("enter message")
words = st.split(" ")
coding = True
if(coding):
  nwords = []
  for word in words:
    if(len(word)>=3):
     r1 = "dsf"
     r2 = "jkr"
     stnew = r1+ word[1:] + word[0] +r2
     nwords.append(stnew)
    else:
      nwords.append(word[::-1])

  print("  ".join(nwords))



else:

  pass



