# -*- coding: utf-8 -*-
"""constructor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JDUevIVkuDPqffrAaKN9DGUZuvnEeTrw
"""

class person:
  name = "qurat"
  occ = "developer"

  def info(self):
    print(f"{self.name} is a {self.occ}")
a = person()
print(a.name)

class person:
  name = "qurat"
  occ = "developer"

  def info(self):
    print(f"{self.name} is a {self.occ}")
a = person()
a.info()



class person:
  def __init__(self,n,o):
    print("hey i am a person")
    self.name = n
    self.occ = o


  def info(self):
    print(f"{self.name} is a {self.occ}")
a = person("qurat","developer")
b = person("aisha","HR")

a.info()
b.info()