# -*- coding: utf-8 -*-
"""Copy of feb17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ITlphXJpXXNksUOreEmWForBpGUEd7aC
"""

a = input("Enter the number: ")

try:
  for i in range(1,11):
    print(f"{int(a)} X {i} = {int(a)*i}")
    print("Multiplication table of {a} is: ")
except Exception as e:
  print(e)

  print("invalid input")

