# -*- coding: utf-8 -*-
"""Copy of revision1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CWa4odp9n9INCtimhzlffoBglWVl8Auq
"""

print("hello world")

print('3')

var =10
print(var)

varr = "Qalb"
print(varr)

## _ is the only alphanumeric character that can be included in variable name
var_ ="qurat"
print(var_)

## variable names cannnot start with number but it may include numbers
## keywords are predefined words and keywords cannot be used as variable name