# -*- coding: utf-8 -*-
"""cwhfunctions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18Y9gJn-76WOe1SbyGRdqx5kQlmgvrF_w
"""

def gmean (a,b):
  mean = (a*b)/(a+b)
  print(mean)

a=9
b=8
gmean(a,b)

if (a>b):
  print("first number is greater")
else:
  print("Second number is greater")

def isgreater(a,b):
  if(a>b):
    print("first number is greater")
  else:
    print("second number is greater or equal")



def islesser(a,b):
  pass

isgreater(a,b)
gmean(a,b)

def average(a=9, b=1):
  print("the average is ", (a+b)/2)

average(a=2, b=2)

average(b=9, a=21)

def average(a, b=1, c=1 ):
  print("the average is ", (a+b)/2)

average(a=2, b=2)

def name(fname, mname ="xyz",lname = "abc" ):
  print("hello,", fname, mname, lname)

name("qurat", "insha", "aisha")

# required arguments
def average(a,b,c):
  print("the average is ", (a+c)/2)

average(b=2,a=6, c=0)  # order doesn't matter in arguments

def average(*numbers):
  # print(tuple)
  sum = 0
  for i in numbers:
    sum = sum + i
  print("average is:", sum/len(numbers))
  return 7

  #return sum/len(numbers)

c = average(5,6,7,8,3,1)
print("value of c is",c)      """ DOUBT """

