# -*- coding: utf-8 -*-
"""day7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15Bj9SLtZA8MSZWJpGnW4VkUlmWOKaBNh
"""

list1 = [20,15,50,30,10]
print(list1)

list1.sort()
print(list1)

list1.insert(1,2)
print(list1)

list1

list1.remove(30)
print(list1)

print(list1)
print(list1)

list1.sort(reverse=True)
print(list1)

list1.clear()