# -*- coding: utf-8 -*-
"""decorators.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e0hseDz_lcIz-774iCKPyVqPzqjZ9s2u
"""

def hello():
  print("hello world")

def greet(fx):
  def mfx():
    print("Good Morning")
    fx()
    print("thanks for using this function")
  return mfx
hello()

def greet(fx):
  def mfx():
    print("Good Morning")
    fx()
    print("thanks for using this function")

  return mfx
@greet
def hello():
   print("hello world")


hello()

def greet(fx):
  def mfx():
    print("Good Morning")
    fx()
    print("thanks for using this function")

  return mfx
@greet
def hello():
   print("hello world")

def greet(fx):
  def mfx(*args, **kwargs):
    print("Good Morning")
    fx(*args, **kwargs)
    print("thanks for using this function")

  return mfx
@greet
def hello():
   print("hello world")


def add(a,b):
  print(a+b)
hello()
greet(add)(1,2)

def greet(fx):
  def mfx():
    print("Good Morning")
    fx()
    print("thanks for using this function")

  return mfx
@greet
def hello():
   print("hello world")

def greet(fx):
  def mfx(*args, **kwargs):
    print("Good Morning")
    fx(*args, **kwargs)
    print("thanks for using this function")

  return mfx
@greet
def hello():
   print("hello world")

@greet
def add(a,b):
  print(a+b)
hello()
#greet(add)(1,2)

