# -*- coding: utf-8 -*-
"""Exceptionhandling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fMpgEG44Dy7bzTq5pijiCIGWt2dpRmQM
"""

try:
    num = int(input("Enter an integer: "))
except ValueError:
    print("Number entered is not an integer.")

# else block is executed when there is no error in try block.


try:
    num = int(input("Enter an integer: "))
except ValueError:
    print("Number entered is not an integer.")
else:
    print("Integer Accepted.")

# finally block is execute whatever is the outcome of try……except…..else blocks.
try:
    num = int(input("Enter an integer: "))
except ValueError:
    print("Number entered is not an integer.")
else:
    print("Integer Accepted.")
finally:
    print("This block is always executed.")

