# -*- coding: utf-8 -*-
"""Exercise6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QfDU6pqGHCktIbGx-RsYxRCYALnssMWz
"""

class library:
  def __init__(self):
    self.nobooks = 0
    self.books = []

  def addbook(self, book):
    self.books.append(book)
    self.nobooks = len(self.books)

  def showinfo(self):
    print(f"the library has {self.nobooks} books")

    for book in self.books:
      print(book)
l1 = library()
l1.addbook("harry potter2")
l1.addbook("harry potter3")
l1.addbook("harry potter4")
l1.showinfo()