# -*- coding: utf-8 -*-
"""exercise3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A3kiYSsnAz5nki36SNDpWW5fw-EgaASf
"""

print("Let's play the Game!!!")
questions =["1.Who is the PM of India?" , " 2.What is the national game of India?" , " 3.What is the Capital of India?"]
options=["a.Narendra Modi" "b.Rahul Gandhi" "c.Arvind Kejriwal" "d.Amit Shah" , "a.Hockey" "b.Cricket" "c.Rubgy" "d.Chess" , "a.Mumbai " "b.New Delhi " "c.Pune " "d.Punjab "]
correct_options=["a" , "a" ,"b" ]
prize_money =[1000 , 10000,25000]
Prize_earned =0
for i in range(0,len(questions)):
  print(questions[i])
  print(options[i])
  print(prize_money[i])
  user_input=input("Enter the correct option: ")
  if(user_input == correct_options[i]):
    print("You entered the correct option")
    Prize_earned = Prize_earned + prize_money[i]
  else:
    print("You entered the wrong option and have lost the game!!!")
    break
print(Prize_earned)