# -*- coding: utf-8 -*-
"""Feb06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jwux0Iro64HP1Ej8nMN0OwgTl_fioSPe
"""

# set is an unordered collection with no duplicate elements.
basket = {'apple', 'orange', 'apple', 'pear', 'orange', 'banana'}
print(basket)                      # show that duplicates have been removed

'orange' in basket          # fast membership testing

'cherry' in basket

# Demonstrate set operations on unique letters from two words

a = set('afradadafra')
b = set('alacazam')

b                                  # unique letters in b

a                                  # unique letters in a

a - b              # letters in a but not in b

a | b                      # letters in a or b or both

a & b                              # letters in both a and b

a ^ b                              # letters in a or b but not both

# dictionary
name = {'jack': 4098, 'melo': 4139}
name ['kim'] = 4127
name

name['jack']

del name['melo']
name ['suzi'] = 4127
name

list(name)

sorted(name)

'kim' in name

'jack' not in name