# -*- coding: utf-8 -*-
"""Feb05.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18crNsCnpJCadNUJRIkP_hw6KSadjkmzv
"""

# while loop
x = 0
while (x < 5):
    x = x + 1
    print("Hello World")

# while loop with else statment
a = 0
while (a < 3):
    a = a + 1
    print("Hello World")
else:
    print("In Else Block")

# Prints out 0,1,2,3,4

count = 0
while True:
    print(count)
    count += 1
    if count >= 5:
        break

# Prints out only odd numbers - 1,3,5,7,9
for x in range(10):
    # Check if x is even
    if x % 2 == 0:
        continue
    print(x)

# Prints out only even numbers - 0,2,4,6,8
for x in range(10):
    # Check if x is even
    if x % 2 == 1:
        continue
    print(x)

# Python program to demonstrate ternary operator
a, b = 10, 20

print( (b, a) [a < b] )