# -*- coding: utf-8 -*-
"""feb19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dxSkPThsx3scE9sB491mmSl1FCG5qTe7
"""

# tuple value cant be changed, length cant be changed
# tuples, strings and lists are immutable
tup = (1,2,3,4,5)
print(type(tup),tup)

tup = (15)
print(type(tup),tup)

tup = (1,)
print(type(tup),tup)

tup = (1,2,"red",True)
print(type(tup),tup)
print(tup[0])
print(tup[1])
print(tup[2])
print(tup[3])
#print(tup[40]) --- will show  error as there is no such value
print(tup[2])
print(len(tup))
print(tup[-1])
print(tup[-2])
print(tup[-3])
print(tup[-4])

if 2 in tup:
  print("yes 2 is present in this tuple")

if 22 in tup:
  print("yes 2 is present in this tuple")

tup2 = tup[0:2]    # prints index 0 to index1, excluding the index 2
 print(tup2)

tup3 = tup[:3]    # means index 0 to index 3
print(tup3)

tup3 = tup[2:]    # means index 2 to length of tup
print(tup3)

#tuple methods
countries = ('spain','Italy', 'Russia','India','Germany','Canada')
temp = list(countries)
temp.append('England')
temp.pop(3)
temp[2] = 'Finland'    # at index 2
countries = tuple(temp)
print(countries)

country = ("Spain", "Italy", "India", "England", "Germany")
#            [0]      [1]      [2]       [3]        [4]
print(country[-1])
print(country[-3])
print(country[-4])

country = ("Spain", "Italy", "India", "England", "Germany")
if "Germany" in country:
    print("Germany is present.")
else:
    print("Germany is absent.")

country = ("Spain", "Italy", "India", "England", "Germany")
if "Russia" in country:
    print("Russia is present.")
else:
    print("Russia is absent.")

animals = ("cat", "dog", "bat", "mouse", "horse", "donkey", "goat", "cow")
print(animals[3:6])     #using positive indexes
print(animals[-6:-2])   #using negative indexes

animals = ("cat", "dog", "bat", "mouse", "horse", "donkey", "goat", "cow")
print(animals[:6])      #using positive indexes
print(animals[:-3])

animals = ("cat", "dog", "bat", "mouse", "pig", "horse", "donkey", "goat", "cow")
print(animals[::2])     #using positive indexes
print(animals[-8:-1:2]) #using negative indexes

countries = ("Pakistan", "Afghanistan", "Bangladesh", "ShriLanka")
countries2 = ("Vietnam", "India", "China")
southEastAsia = countries + countries2
print(southEastAsia)