# -*- coding: utf-8 -*-
"""feb16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1apyNBh_nwIOPRL70_fqE361aY9hcuKJ4
"""

name = 'Qurat'
for i in name:
    print(i, end=", ")

colors = ("Red", "Green", "Blue", "Yellow")
for x in colors:
    print(x)

for k in range(5):
    print(k)

for k in range(4,9):
    print(k)

count = 5
while (count > 0):
    print(count)
    count = count - 1

x = 5
while (x > 0):
    print(x)
    x = x - 1
else:
    print('counter is 0')

for i in range(1,10):
    if(i%2 == 0):
        continue
    print(i)

i = 1
while (i <= 10):
    i = i + 1
    if (i%2 != 0):
        continue
    print(i)

for i in range(1, 4):
    k = 1
    while (k<=3):
        print(i, "*", k, "=", (i*k))
        k = k + 1
    print()

i = 1
while (i <= 10):
    i = i + 1
    if (i == 5):
        break
    print(i)

for i in range(1, 10):
    print(i)
    if (i == 5):
        break