# -*- coding: utf-8 -*-
"""feb10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1djVZbsfkMw7jgwtQnNkgsM3Xpx6aOSwY
"""

# abs function
#  integer number
integer = -56
print('Absolute value of -56 is:', abs(integer))

#  floating number
floating = -40.83
print('Absolute value of -40.83 is:', abs(floating))

# all values true
k = [1, 3, 4, 6]
print(all(k))

# all values false
k = [0, False]
print(all(k))

# one false value
k = [1, 3, 7, 0]
print(all(k))

# one true value
k = [0, False, 5]
print(all(k))

# empty iterable
k = []
print(all(k))

# bin function
x =  10
y =  bin(x)
print (y)

# python bool
test1 = []
print(test1,'is',bool(test1))
test1 = [0]
print(test1,'is',bool(test1))
test1 = 0.0
print(test1,'is',bool(test1))
test1 = None
print(test1,'is',bool(test1))
test1 = True
print(test1,'is',bool(test1))
test1 = 'Easy string'
print(test1,'is',bool(test1))

# python bytes
string = "Hello World."
array = bytes(string, 'utf-8')
print(array)

# pyhon callable
x = 8
print(callable(x))

# exec funstion
x = 8
exec('print(x==8)')
exec('print(x+4)')

s = sum([1, 2,4 ])
print(s)

s = sum([1, 2, 4], 10)
print(s)

# any function
l = [4, 3, 2, 0]
print(any(l))

l = [0, False]
print(any(l))

l = [0, False, 5]
print(any(l))

l = []
print(any(l))

# ascii function
normalText = 'Python is interesting'
print(ascii(normalText))

otherText = 'Pythön is interesting'
print(ascii(otherText))

print('Pyth\xf6n is interesting')



