# -*- coding: utf-8 -*-
"""feb13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lsZJPpoiuniA_Mh2_owtISrrjEdQe1BA
"""

# Python program to get average of a list
def calc_average(lst):
    return sum(lst) / len(lst)
lst = [1,2,3,4,5,6,7,8,9,10]
average = calc_average(lst)
# Printing the average value of the list
print("The average of the list is ", round(average, 3))

P = "python "
Q = "cloud "

print ("Variables Value Before Swapping: ")
print ("Value of P: ", P)
print ("Value of Q: ", Q)

# Method to swap 'P' and 'Q'
P, Q = Q, P

print ("Variables Value After Swapping: ")
print ("Value of P: ", P)
print ("Value of Q: ", Q)

print(round(16))

# For floating point
print(round(25.8))
print(round(25.4))