# -*- coding: utf-8 -*-
"""feb18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NPIOZ4KnVFlDeMJ8tZPtp_KjXPolnk6W
"""

import math

print("Sin(0) =", math.sin(0))
print("Sin(30) =", math.sin(math.pi/6))
print("Sin(45) =", math.sin(math.pi/4))
print("Sin(60) =", math.sin(math.pi/3))
print("Sin(90) =", math.sin(math.pi/2))

def add(a, b):
    return (a+b)

def sub(a, b):
    return (a-b)

def mul(a, b):
    return (a*b)

def div(a, b):
    return (a/b)

import math as m

print("Square Root of 36 :", m.sqrt(36))
print("3 to the power of 4 :", m.pow(3,4))

from operator import mod
import math

lst1 = dir(math)
print(lst1)