# -*- coding: utf-8 -*-
"""getter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OJJOUs6rMpxpZTXZnKRpsF4nBPumcRSm
"""

class Myclass:
  def __init__(self,value):
    self._value = value
  def show(self):
    print(f"value is {self._value}")
  @property
  def value(self):
    return self._value

obj = Myclass(10)
obj.show()

class Myclass:
  def __init__(self,value):
    self._value = value
  def show(self):
    print(f"value is {self._value}")
  @property
  def value(self):
    return self._value

obj = Myclass(10)
print(obj._value)
obj.show()

class Myclass:
  def __init__(self,value):
    self._value = value
  def show(self):
    print(f"value is {self._value}")
  @property
  def ten_value(self):
    return 10*self._value

obj = Myclass(10)
print(obj.ten_value)
obj.show()

class Myclass:
  def __init__(self,value):
    self._value = value
  def show(self):
    print(f"value is {self._value}")
  @property
  def ten_value(self):
    return 10*self._value
  @ten_value.setter
  def ten_value(self,new_value):
    self._value = new_value/10

obj = Myclass(10)
obj.ten_value = 67
print(obj.ten_value)
obj.show()