# -*- coding: utf-8 -*-
"""inheritance.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YuDOMS2M2KFibDGR666leV-jdZHo8V0p
"""

class employee:
  def __init__(self, name, id):
    self.name = name
    self.id = id

  def showdetails(self):
    print(f"the name of the employee: {self.id} is {self.name}")
e = employee("Rohan",40)
e.showdetails()

class employee:
  def __init__(self, name, id):
    self.name = name
    self.id = id

  def showdetails(self):
    print(f"the name of the employee: {self.id} is {self.name}")

class programmer(employee):    # programmer is made from employee class
  def showlanguage(self):
    print("the default language is python")

e1 = employee("Rohan",40)
e1.showdetails()
e2 = programmer("Sam",56)     # it will inherit property/methods from employee
e2.showdetails()
e2.showlanguage()