# -*- coding: utf-8 -*-
"""is _==.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K75pKEwbV5MRs2nn7oJSFgcgWnrroJln
"""

a = 4
b = "4"
print(a is b) #exact location of obj in memory
print(a == b)

a = [2,3,4]
b = [2,3,4]
print(a is b) #exact location of obj in memory
print(a == b)

a = (1,2)
b = (1,2)
print(a is b) #exact location of obj in memory
print(a == b)

a = "harry"
b = "harry"
print(a is b) #exact location of obj in memory
print(a == b)

a = None
b = None
print(a is b) #exact location of obj in memory
print(a == b)

a =
b =
print(a is b) #exact location of obj in memory
print(a == b)