# -*- coding: utf-8 -*-
"""lambda.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dpldvJCxvVZPkn8FZgLPSHdYBOIToB1t
"""

def triple(x):
  return x*3

print(triple(5))

cube = lambda x: x*x*x
triple = lambda x: x*3
print(triple(4))
print(cube(5))

avg = lambda x,y,z:(x+y+z)/3
print(avg(1,2,3))

#function passed to a function

# cube function without name cube (anonymous)
def apple(fx,value):
  return  fx(value)

print(apple(lambda x:x*x*x,2))



