# -*- coding: utf-8 -*-
"""magic_method.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L9yM52OD9ABDrGFH4f3cBYHNEakzRJ9C
"""

# magic methods or dunder methods -- starts with double underscore (__)
class  employee:
  name = "Qurat"

e = employee()
print(e.name)

class  employee:
  name = "Qurat"
  def __len__(self):
    i = 0
    for c in self.name:
      i = i + 1
    return i

e = employee()
print(e.name)
print(len(e))

class  employee:
  def __init__(self,name):
    self.name = name

  def __len__(self):
    i = 0
    for c in self.name:
      i = i + 1
    return i

e = employee("Qurat")
print(e.name)
print(len(e))



