# -*- coding: utf-8 -*-
"""matchcase.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mqy_hZMB4OAh7RFZcUlmea6YhrNUqF5y
"""

x = int(input("Enter the value of x from 1-7 : "))
match x:
  case 1:
    print("It is Monday")
  case 2:
    print("It is Tuesday")
  case 3:
    print("It is Wednesday")
  case 4:
    print("It is Thursday")
  case 5:
    print("It is Friday")
  case 6:
    print("It is Saturday")
  case _:
    print("It is Sunday")