# -*- coding: utf-8 -*-
"""Multiple_inheritance.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TR4H09Aza1aytcfLW-OH0lQ2KlX9XcSC
"""

class employee:
  def __init__(self, name):
    self.name = name

class dancer:
  def __init__(self, dance):
    self.dance = dance

class danceremployee(employee, dancer):
  def __init__(self, dance, name):
    self.dance = dance
    self.name = name

o = danceremployee("kathak", "shivani")
print(o.name)
print(o.dance)

class employee:
  def __init__(self, name):
    self.name = name

  def show(self):
    print(f"the name is {self.name}")

class dancer:
  def __init__(self, dance):
    self.dance = dance

  def show(self):
    print(f"the name is {self.dance}")

class danceremployee(employee, dancer):   #if we will change order here,mro will changenge
  def __init__(self, dance, name):
    self.dance = dance
    self.name = name

o = danceremployee("kathak", "shivani")
print(o.name)
print(o.dance)
o.show()

print(danceremployee.mro())



class dancer:
  def __init__(self, dance):
    self.dance = dance

  def show(self):
    print(f"the name is {self.dance}")

class danceremployee(dancer, employee):   #if we will change order here,mro will changenge
  def __init__(self, dance, name):
    self.dance = dance
    self.name = name

o = danceremployee("kathak", "shivani")
print(o.name)
print(o.dance)
o.show()

print(danceremployee.mro())