# -*- coding: utf-8 -*-
"""python5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y7gGsnBcTAFFgidTFJ7ggOrkZNtk56m3
"""

##python indentation
print("abc")





print("xyz")
print("abc")

##conditions in python
num = 10
if num > 5 :
  print(" if stmt executed")
  print(" second cmd inside if stmt")
  print(num*10)

## comparison operation
a = 12
#### equal to comparison happens using "=="
if a == 10:
 print("A is equal to 10")

if a!=12:
 print(" A is not equal to 10")

## assignment operaators
x = 12
print(x)

x += 1
print("x")

x-= 1
print ("x")

x -= 1
print("x")

num3 = 19
num4 = 7
print(num3%num4)

nu



x = 2
y = 3
z=4
print(x*y)
print(x**y)
print(y**x)
print(x*y*z)
print(x**y)

q

q = 1 + 2 * 3
print(q)

num10 = 15
if num10 > 16:
 print("it is greater than 16")
else:
 print("less than 16")

if num10 > 16:
   print(" greater than 16")
elif num10> 10:
   print("greater than 10 but less than 16")
else:
  print("less than or equal to 16")

num1 = 1
num2 = 2
print(num1-num2)

if 10>5 :
  print("this condition is true")
  print("second line")