# -*- coding: utf-8 -*-
"""python4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s1JvI0zLiR_ZZmrvfXPiKqtdxKhRPoyW
"""

classMarksEnglish=[18,19,17,16,20,12,13]

## python -0 based indexing!

##  Access an element of a list
print(classMarksEnglish[0])

classMarksEnglish[1]

print(classMarksEnglish[4])

## changing elements of a list
print(classMarksEnglish)

classMarksEnglish[5]=20

print(classMarksEnglish[5])

print(classMarksEnglish)

len(classMarksEnglish)

##Range of values
## day 2  -> day 6

print(classMarksEnglish[2:6])

## appending the elements
## list.append (value)
## it always gets appended to the last
classMarksEnglish.append(10)

print(classMarksEnglish)

## inserting an element at a specific index
## list.insert(index at which you want to insert , value to be inserted)
classMarksEnglish=[18,19,17,16,20,12,13]
classMarksEnglish.insert(2,10)
print(classMarksEnglish)

print(classMarksEnglish)

## remove

classMarksEnglish=[18,19,17,16,20,12,13]

classMarksEnglish.remove(19)
print(classMarksEnglish)

