# -*- coding: utf-8 -*-
"""single_inheritance.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j5UIbz7AfDmwXeYztVTAQJc_E_oUSDwm
"""

class Animal:
  def __init__(self, name, species):
    self.name = name
    self.species = species

  def make_sound(self):
    print("Sound made by the Animal")

class Dog(Animal):
  def __init__(self, name, breed):
    Animal.__init__(self, name, species = "Dog")
    self.breed = breed

  def make_sound(self):
    print("Bark!")

  d = Dog("Dog", "Doggerman")
  d.make_sound()

  a = Animal("Dog", "Dog")
  a.make_sound()