# -*- coding: utf-8 -*-
"""Snakewatergun.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MewkHoVnOP0jrHs5Lh_xxqGdSxXM7ruH
"""

import random
def check(computer, user):

  if(computer == user):
    return 0
  if(computer == 0 and user == 1):
    return -1
  if(computer == 1 and user == 2):
    return -1
  if(computer == 2 and user == 0):
    return -1

  return 1

computer = random.randint(0,2)
user = int(input("Enter 0 for Snake, 1 for Water, 2 for Gun:\n"))
score = check(computer, user)

print("You:",user)
print("Computer: ",computer)

if (score == 0):
  print("Its a draw")
elif(score == -1):
  print("You lose")
else:
  print("You won")