# -*- coding: utf-8 -*-
"""staticmethod.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tBj00K0xQzWrRwZ0YEQaUHRXhky0Vmv9
"""

class math:
  @staticmethod
  def add(a,b):
    return a+b

result = math.add(1,2)
print(result)

class math:
  def __init__(self,num):
    self.num = num

  def addtonum(self,n):
    self.num = self.num +n

  @staticmethod   # static method can be called normally, without instance
  def add(a,b):
    return a+b

a = math(5)
print(a.num)
a.addtonum(6)
print(a.num)
print(math.add(7,2))