# -*- coding: utf-8 -*-
"""time_module.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/166NErZjDcnt4hVlcTT6KXSeh33GJ-ALp
"""

import time
print(time.time())

import time

def usingWhile():
  i = 0
  while i<50000:
    i = i+1
    print(i)

def usingFor():
  for i in range(50000):
    print(i)
init = time.time()  # return the time in seconds since epoch
usingFor()
t1 = time.time() - init
#print(time.time() - init)   # time() float-- return the current time in seconds
init = time.time()
usingWhile()
print(time.time() - init)
print(t1)

print(4)
time.sleep(10)
print("this is printed after 10 seconds")

t = time.localtime()
formatted_time = time.strftime("%Y-%m-%d %H:%M:%S",t)
print(formatted_time)