# -*- coding: utf-8 -*-
"""timeExercise.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/103Y6yz_YzG5bZealFSmsnKpDRNsCx3Yb
"""

import time
t = time.strftime('%H:%M:%S')

hour = int(time.strftime('%H'))
#hour = int(input("Enter hour: "))

if(hour>0 and hour<12):
  print("Good Morning")
elif(hour>=12 and hour<17):
  print("Good Afternoon")
elif(hour>=17 and hour<0):
  print("Good Night")