# -*- coding: utf-8 -*-
"""Walrus.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O5lt18P00-opFJc-7oTgOPGC--6MLahE
"""

#walrus    := can be used in variety of contexts. it assigns value to variables as per of larger expression

#a = True
#print(a:=False)
numbers = [1,2,3,4,5]

while(n := len(numbers)) > 0:
  print(numbers.pop())

happy = False
print(happy)

print(happy := True)

foods = list()
while True:
  food = input("What food do you like?")
  if food == "quit":
      break
  foods.append(food)

a = True
print(a:=False)

foods = list()
while (food := input("What food do you like?")) != "quit":
  foods.append(food)